# ─── LOCAL ENVIRONMENT (Laptop) ─────────────────────────────
# Generated by Terraform — Kafka/MongoDB run on the Droplet
# Droplet IP: ${droplet_ip}
# ────────────────────────────────────────────────────────────

services:
  # ─── OpenTelemetry (Jaeger) ──────────────────────────────
  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: rationalization-jaeger-local
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "5778:5778"    # Configs for agents
      - "9411:9411"    # Zipkin compatible endpoint
    restart: unless-stopped

  # ─── Kafka UI ────────────────────────────────────────────
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rationalization-kafka-ui-local
    ports:
      - "9333:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "rationalization-cloud"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "${droplet_ip}:9092"
    restart: unless-stopped

  # ─── Redis ───────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: rationalization-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      TZ: Asia/Bangkok
    restart: unless-stopped

volumes:
  redis_data:

# ─── Connection Info ───────────────────────────────────────
# MongoDB:  mongodb://${droplet_ip}:27017/?directConnection=true
# Kafka:    ${droplet_ip}:9092
# Redis:    localhost:6379
# Jaeger:   localhost:4317 (OTLP gRPC)
# Kafka UI: http://localhost:9333
